# Generated by Django 4.2.1 on 2023-06-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Contact',
        ),
    ]
