# Generated by Django 4.2.1 on 2023-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveApp', '0002_rename_message_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
